FROM postgres

### Install Java, Unzip
RUN apt-get update && apt-get install -y \
    unzip
### openjdk-7-jdk

RUN add-apt-repository ppa:webupd8team/java
RUN apt-get update
RUN apt-get install oracle-java8-installer
RUN apt-get install oracle-java8-set-default
RUN update-alternatives --config java
RUN update-alternatives --config javac

ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres

### setup gui
RUN mkdir /var/www
COPY pgstudio_2.0-bin.zip /var/www
RUN unzip /var/www/pgstudio_2.0-bin.zip -d /var/www

### Expose ports for this container
EXPOSE 8080 80 5432
### run gui + postgres db
### TODO we shouldn't run this as root - it doesn't run at start anyway.. dunno why
RUN bash /var/www/pgstudio_2.0-bin/bin/catalina.sh start